apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: leech-go 
  janus-idp.io/tekton: leech-go
  backstage.io/kubernetes-id: leech-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: leech-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  